apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: voting-app-ingress
  namespace: voting
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: vote.107.20.228.88.nip.io # Replace with your actual domain or get the ip address by running nslookup+alb_dns then pick the ip address and replace it in the host field.
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: vote
            port:
              number: 80

  - host: result.107.20.228.88.nip.io # Replace with your actual domain or get the ip address by running nslookup+alb_dns then pick the ip address and replace it in the host field.
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: result
            port:
              number: 80